packages:
  - docs
  - examples
catalog:
  '@babel/core': ^7.12.16
  '@babel/eslint-parser': ^7.12.16
  '@babel/preset-env': ^7.26.9
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@release-it/conventional-changelog': ^10.0.0
  '@rollup/plugin-json': ^5.0.2
  '@rollup/plugin-node-resolve': ^13.3.0
  '@rollup/plugin-strip': ^2.1.0
  '@vue/cli-plugin-babel': ^4.4.6
  '@vue/cli-plugin-eslint': ^4.4.6
  '@vue/cli-service': ^4.4.4
  commitizen: ^4.3.1
  core-js: ^3.8.3
  cz-git: ^1.11.1
  eslint: ^7.32.0
  eslint-config-prettier: ^7.2.0
  eslint-plugin-prettier: ^3.4.1
  eslint-plugin-vue: ^8.0.3
  html-entities: 1.4.0
  jsdoc: ^4.0.4
  js-yaml: ^4.1.0
  husky: ^9.1.7
  lint-staged: ^15.5.0
  prettier: ^2.8.8
  release-it: ^18.1.2
  rimraf: ^3.0.2
  rollup: ^2.79.2
  rollup-plugin-babel: ^4.4.0
  rollup-plugin-commonjs: ^10.1.0
  rollup-plugin-terser: ^7.0.2
  rollup-plugin-vue: ^5.1.9
  vue: ^2.6.14
  vue-router: ^3.5.3
  vue-template-compiler: ^2.6.14
  vuepress: 1.9.10
  vuepress-plugin-autodoc: ^0.1.7
  vuepress-plugin-demo-container-v2: ^2.3.4
  vxe-pc-ui: 3.9.33
  vxe-table: 3.18.15
  vxe-table-middleware: ^0.3.1
  xe-utils: 3.7.9
