packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  "@babel/preset-env": ^7.26.9
  "@rollup/plugin-json": ^5.0.2
  "@rollup/plugin-node-resolve": ^13.3.0
  "@rollup/plugin-strip": ^2.1.0
  rimraf: ^3.0.2
  rollup: ^2.79.2
  rollup-plugin-babel: ^4.4.0
  rollup-plugin-commonjs: ^10.1.0
  rollup-plugin-terser: ^7.0.2
  rollup-plugin-vue: ^5.1.9
  vue: ^2.6.14
  vxe-pc-ui: ^3.3.97
  vxe-table: ^3.13.5
  xe-utils: ^3.7.2
